tweet_template: "📢 {title} — {price}€ {url}"
sites:
  - id: pccomponentes
    name: PcComponentes Ofertas
    enabled: true
    price_threshold_eur: 99999.0  # Publica todo en la primera ejecución
  - id: amazon
    name: Amazon Ofertas del Día
    enabled: true
    price_threshold_eur: 99999.0
